
services:
    app:
        build:
            context: ./backend
            dockerfile: docker/backend/Dockerfile
        container_name: laravel_app
        volumes:
            - ./backend:/var/www
        ports:
            - 9000:9000
        networks:
            - laravel_react_net
        depends_on:
            - mysql

    frontend:
        build:
            context: ./frontend
            dockerfile: docker/frontend/Dockerfile
        container_name: react_frontend
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app
        networks:
            - laravel_react_net

    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_react_net

volumes:
    db_data:

networks:
    laravel_react_net:
